AllCops:
  TargetRubyVersion: 3.1.3
  NewCops: enable

Metrics/MethodLength:
  Max: 15

Naming/MethodParameterName:
  MinNameLength: 1

Security/Eval:
  Enabled: false

Style/NumberedParametersLimit:
  Max: 2
